version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - external-network

  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8081:8081"
    networks:
      - external-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: order_service_user
      DB_PASS: order_service_pass
      DB_NAME: order_service
      CONTRACT_SERVICE_URL: http://labs-backend-challenge-main-contact-service-1:8080
      KAFKA_BROKER: kafka:9092
      KAFKA_PERSON_EVENTS_CHANGED_TOPIC: personevents-changed
      KAFKA_PERSON_EVENTS_CREATED_TOPIC: personevents-created
      KAFKA_PERSON_EVENTS_DELETED_TOPIC: personevents-deleted
      KAFKA_ORDER_EVENTS_CREATED_TOPIC: orderevents-created
      KAFKA_ORDER_EVENTS_CHANGED_TOPIC: orderevents-changed
      KAFKA_ORDER_EVENTS_DELETED_TOPIC: orderevents-deleted
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  external-network:
    external: true